### ISSUE TITLE
Voortgang na dag 1

### ISSUE THREAD

**Issue by DeWvanAxel** [DeWvanAxel/thesis#3]
## goals 3-4
1. Load data from zoek.bekendmakingen
2. Load data from waaroverheid
3. finish pre-mature version of naive bayes
4. finish pre-mature version of SVM
5. finish pre-mature version of W2V

## successes
1. although I did not use their API but instead used data from other trainees 
2. Dit leek ook vandaag al te lukken, voor nu maakte ik een gigantische csv met organisatie, catergorie van het document (que soort), de tekst en de titel. Alleen op een gegeven moment krijg ik een server response van 500, dus ik overleg morgen met Breyten over wat dat kan zijn.
3. 9 & 16 percent accuracy, de simpele scikit gebruikt. Het is wel een beetje vreemd dat het zo slecht werkt, aangezien er bij de 16 procent maar een categorie of 20 is. Daar moet ik even naar kijken.
4. 6 & 9 percent accuracy, zelfde verhaal als bij 3.
5. Word2Vec is gemaakt op basis van de data van andere stagiars, lijkt redelijk te werken, maar kan meer testdata gebruiken. Later kan de Word2Vec ook getraind worden met de data van 2 erbij.

## challenges
- De data van de gemeentes is best vies, dus die goed schoonmaken is belangrijk
- Het is nog steeds niet helemaal duidelijk hoe CNN werken op lange zinnen, ook dat moet ik uitwerken. Voor nu heb ik drie oplossingen hiervoor. 1. documenten opsplitsen, de zinnen één voor één gebruiken, en als het ware de meeste stemmen gelden. 2. het op de titels/eerste regels toepassen. 3. Een aggregatie maken van woorden naar zinnen, en eventueel van zinnen naar paragrafen. Dit kan met Doc2Vec.

## wat is fijn om af te hebben aan het einde van de week
- API data inladen
- Word2Vec trainen op alle data
- Mogelijkheid creeren meer dat op te halen van bekendmakingen
- Naive Bayes/SVM omhoog krijgen
- CNN methodes uitwerken zodat ik volgende week met Maarten kan brainstormen

**Comment by maartenmarx** [comment]
* Mooi gedaan Axel.
* Wat is precies de taak die je uitvoert, en hoe evalueer je die?
* Je kunt volgens mij ook elders word2vec vectoren voor het NL vinden. Ook bij Google meen ik. 
* Het is goed om contact op te nemen met Tobias over de dataset uit waaroverheid. Hij is daar ook mee bezig.

**Comment by DeWvanAxel** [comment]
- ik zal kijken naar de google word2vec en ik heb ook Tobias een bericht gestuurd. De taak die ik uitvoer is het classificeren van de data van officiele bekendmakingen op basis van de tekst daarin. Voor nu is mijn evaluatie accuracy maar dat bouw ik later nog uit.
- De scores van dinsdag heb ik ondertussen enorm verbeterd, maar door het volgende punt kan ik nog niet rapporteren wat ze zijn.
- Afgelopen dagen niets kunnen programmeren doordat ik problemen heb met Anaconda en jupyter. Ook de UvA helpdesk kon niet helpen, noch het internet. Ik heb besloten om een nieuwe pc te kopen (3 maandjes eerder), dus waarschijnlijk kan ik maandag weer coderen. Dat betekent wel dat ik wat minder heb gedaan dan dat ik op dinsdag aangaf te willen doen. In plaats daarvan wel een inleiding geschreven.

Voor woensdag wil ik bespreken:
o	Introductie feedback
o	aandacht aan naive bayes en SVM, hoe veel in thesis en hoeveel parameter optimalisatie
o	CNN beste methode mee te beginnen
	Doc2Vec
	Per zin, meeste stemmen gelden?
	Average pooling layer voor gooien
	Alleen titel gebruiken/eerste deel
