### ISSUE TITLE
Overzicht data en gridsearch

### ISSUE THREAD

**Issue by DeWvanAxel** [DeWvanAxel/thesis#5]
Vandaag meer overzicht gekregen in de data en gezorgd voor meer grafieken. Daarnaast heb ik de gridsearch laten werken. Tot mijn verbazing schoot de SGD omhoog in klasse naar 97 en 94 procent in acurracy op respectievelijk 18 en 111 onderwerpen. Dit is dusdanig hoog dat ik betwijfel of er nog winst valt te behalen, zeker gegeven de extra trainingstijd met CNN. Wat denk jij daarover?

Ik moet de code nog wel 1 keer helemaal langslopen om te kijken of alles echt klopt,

Zie voor resultaat: https://github.com/DeWvanAxel/thesis/blob/master/Code/Model%20training/Framework.ipynb

**Comment by maartenmarx** [comment]
Wow! 

* Probeer gewoon ook een keer de CNN. Je hebt het toch al zowat klaar staan. 
* Dan wordt de uitdaging dus de transfer learning! 
* Je kunt al eens gaan beginnen met transfer learning BINNEN de overheids data (dus met labels).
       * Splits train/test over tijd: dus oud = train, paar jaar ertussen, en dan nieuw=test.
       * Of splits op heel verschillende types documenten: train op kamervragen, test op weet ik veel.
* In ieder geval heb je dan labels.
* Dus nu is het zaak om je scores heel erg naar beneden te brengen door lastige tests te verzinnen,
* En ze daarna weer op te vijzelen 
 Zet em op!
